apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-api-ingress
  namespace: ai-ops
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  # Route requests via localhost:8080 or with Host: ai-ops.local
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentiment-api-service
            port:
              number: 8000
  - host: ai-ops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentiment-api-service
            port:
              number: 8000
